import Foundation
import SwiftUI

/// One turn in the workspace conversation.
struct ChatTurn: Identifiable, Equatable, Codable {
    enum Role: String, Equatable, Codable { case user, assistant }

    /// Where an answer came from. Shown on the turn itself, because the app
    /// deliberately answers the first question without a model and that is
    /// only honest if it says so — and if the moment it stops being true is
    /// visible too.
    enum Source: String, Equatable, Codable {
        /// Written ahead of time. Needs no model, and says so.
        case written
        /// Generated by the local model just now.
        case model
    }

    /// Live UI rendered as part of a turn.
    ///
    /// The conversation is the workspace, not a lobby in front of one: work
    /// happens *in* the thread. These carry no data of their own — they mark
    /// where a card goes, and the card reads the view model that is actually
    /// running, so a turn from four minutes ago still shows the truth.
    enum Payload: String, Equatable, Codable {
        case none
        /// Progress of the run this turn started.
        case job
        /// The finished transcript, editable in place.
        case transcript
        /// What can be saved, and what each costs.
        case exports
        /// Choosing a look, and spending the re-encode.
        case styles
        /// The re-encode running.
        case burning
        /// The finished video, playable in place.
        case result
        /// A finished recording that has its own screen.
        case meeting
    }

    var id = UUID()
    let role: Role
    var text: String
    /// Still being typed out — the bubble shows a caret and the composer stays shut.
    var isStreaming: Bool = false
    /// The model is reasoning and nothing visible has arrived yet. Said plainly
    /// rather than left as an empty bubble: the thinking itself is never shown,
    /// so without this the wait is indistinguishable from a hang.
    var isThinking: Bool = false
    /// A file handed over in this turn, rendered as a chip rather than a path.
    var attachment: String?
    var source: Source?
    /// Renders the two capability cards under the opening answer.
    var showsCapabilityCards: Bool = false
    var payload: Payload = .none
    /// Material pasted in with the question rather than typed as part of it.
    /// Rendered as a chip and never as a wall of text, but sent to the model in
    /// full — it is the reason the question was asked.
    var pasted: String?
    /// What this answer cost, on the turn it belongs to. Only ever set on a
    /// turn the model produced — a written answer has no rates to report, and
    /// inventing plausible ones for it would be the exact dishonesty the
    /// "written answer · no model needed" badge exists to prevent.
    var stats: ChatStats?
}

/// What the workspace says before it has been given anything.
///
/// The first answer is written, not generated, and is typed out at reading
/// speed while the real model loads behind it. Two reasons, and neither is
/// decoration: a cold local model takes seconds to become resident, and a
/// first impression is exactly where a small model is most likely to invent a
/// feature. Once the canned reply has finished, every later question goes to
/// the model, which is grounded in the same capability sheet (`chat.py`).
@MainActor
@Observable
final class WorkspaceChatVM {
    /// Written answer to "what can you do?". The prose is deliberately short —
    /// the substance is in the cards that follow it, where each way out is
    /// listed with what it costs. Its counterpart for the model lives in
    /// `src/piko/commands/chat.py`.
    static let capabilities = "Two things, both entirely on this Mac."

    /// Questions worth asking once there is a model to answer them. Offered
    /// only after it is up, so a suggestion is never a dead end.
    static let followUps = [
        "Can it handle a three-hour recording?",
        "Which languages does it understand?",
        "How much RAM does this need?"
    ]

    /// What is said the moment a file is handed over. Written rather than
    /// generated: the work has already started by the time this appears, and
    /// making somebody wait on a model to be told so would be theatre.
    static func acknowledgement(for name: String, focus: ArtifactFocus) -> String {
        switch focus {
        case .meeting:
            return "Got **\(name)**. It looks like a conversation, so I'm transcribing it "
                + "and it'll appear below, with a summary one press away."
        case .video, .none:
            return "Got **\(name)**. Transcribing it now — every line with its timecode "
                + "appears below, and subtitle files are ready the moment it finishes. "
                + "Burning them into the picture is a separate press, so nothing is "
                + "re-encoded unless you ask."
        }
    }

    var turns: [ChatTurn] = []
    var draft: String = ""

    /// A large paste, held beside the composer instead of inside it.
    ///
    /// A pasted transcript is not a sentence someone typed — it is material,
    /// and `TextField(axis: .vertical)` lays out every character of it to work
    /// out how tall to be. Thirty thousand characters of that is a main-thread
    /// text layout the app does not come back from: measured at 25–50 seconds
    /// per frame, which is not slowness, it is a hang. So it never enters the
    /// field.
    private(set) var pasted: String?

    /// Whether the composer holds the keyboard right now.
    ///
    /// On the view model rather than read from `@FocusState` inside the paste
    /// monitor: that closure escapes, so it captures a *copy* of the view made
    /// when the monitor was installed, and the focus it sees is frozen at
    /// whatever it was on the first frame — false, forever. A reference type is
    /// the only thing an escaping closure can read a current value from.
    var isComposerFocused = false

    /// Above this, a paste is material rather than a sentence. Eight lines of
    /// quoted text still types fine; four hundred does not.
    static let pasteThreshold = 1_500

    func attachPaste(_ text: String) {
        pasted = ((pasted.map { $0 + "\n\n" } ?? "") + text)
    }

    func dropPaste() {
        pasted = nil
    }

    private(set) var isAnswering = false

    /// Slash suggestions for the current draft.
    var commandSuggestions: [ChatCommand] { ChatCommand.matching(draft) }

    private let backend = BackendService()
    private var streamTask: Task<Void, Never>?

    // MARK: - The opening move

    /// The written introduction, offered as a suggestion rather than demanded
    /// as a toll. It used to be the *only* thing the composer would accept
    /// until it had been asked — which is a box that refuses to be typed in,
    /// and no amount of reasoning makes that read as anything but broken.
    func askWhatItCanDo(warmup: @escaping () -> Void) {
        guard !isAnswering, turns.isEmpty else { return }
        turns.append(ChatTurn(role: .user, text: "What can you do?"))
        // The model starts loading now, so it is resident by the time the
        // written answer has finished typing and a real question arrives.
        warmup()
        typeOut(Self.capabilities)
    }

    /// Reveal a written answer at reading speed.
    ///
    /// Deliberately not instant: an answer that appears whole reads as a
    /// canned page, and one that types out reads as an answer. It also gives
    /// the model the seconds it needs to become resident.
    private func typeOut(_ text: String, cards: Bool = true) {
        isAnswering = true
        turns.append(ChatTurn(role: .assistant, text: "", isStreaming: true,
                              source: .written, showsCapabilityCards: cards))
        let index = turns.count - 1

        streamTask?.cancel()
        streamTask = Task { [weak self] in
            for word in text.split(separator: " ", omittingEmptySubsequences: false) {
                if Task.isCancelled { break }
                try? await Task.sleep(for: .milliseconds(18))
                guard let self, index < turns.count else { return }
                turns[index].text += turns[index].text.isEmpty ? String(word) : " " + word
            }
            guard let self, index < turns.count else { return }
            turns[index].isStreaming = false
            turns[index].isThinking = false
            isAnswering = false
        }
    }

    // MARK: - Files

    /// Take a file handed over in the conversation.
    ///
    /// The chat is the way in, not a description of one. The turn is recorded
    /// before anything is decided so the file is visibly *received*, and the
    /// reply is written rather than generated because the work has already
    /// begun by the time it is read.
    func attach(_ url: URL, focus: ArtifactFocus) {
        cancel()
        let name = url.lastPathComponent
        turns.append(ChatTurn(role: .user, text: "", attachment: name))
        turns.append(ChatTurn(role: .assistant,
                              text: Self.acknowledgement(for: name, focus: focus),
                              source: .written,
                              payload: .job))
    }

    /// The run this conversation started has finished. Its result is written
    /// into the thread rather than onto another screen: the conversation is
    /// the workspace, and being moved out of it mid-thought is the thing the
    /// whole arrangement is trying to avoid.
    func jobFinished(_ payload: ChatTurn.Payload, text: String) {
        guard turns.contains(where: { $0.payload == .job }) else { return }
        guard !turns.contains(where: { $0.payload == payload }) else { return }
        turns.append(ChatTurn(role: .assistant, text: text, source: .written, payload: payload))
    }

    /// Ask for a look. The re-encode is not started here — the card that
    /// appears is where it is spent, deliberately behind one more press.
    func openStyles() {
        guard !turns.contains(where: { $0.payload == .styles }) else { return }
        turns.append(ChatTurn(
            role: .assistant,
            text: "Pick a look. This is the one step that rewrites the video — "
                + "everything above was free.",
            source: .written,
            payload: .styles
        ))
    }

    /// The burn has started. Its progress replaces nothing: the style card
    /// stays, so the choice that produced this render is still on screen.
    func burnStarted() {
        turns.removeAll { $0.payload == .burning || $0.payload == .result }
        turns.append(ChatTurn(role: .assistant, text: "", source: .written, payload: .burning))
    }

    func burnFinished() {
        turns.removeAll { $0.payload == .burning }
        guard !turns.contains(where: { $0.payload == .result }) else { return }
        turns.append(ChatTurn(role: .assistant, text: "", source: .written, payload: .result))
    }

    /// Stopped halfway. The progress card goes and nothing takes its place —
    /// a result card here would be claiming a video that was never written.
    func burnCancelled() {
        turns.removeAll { $0.payload == .burning }
    }

    /// Drop the live cards when the thing they were showing is gone.
    func clearWork() {
        turns.removeAll { $0.payload != .none }
    }

    // MARK: - Real questions

    /// Answer a recognised request with the app itself rather than with prose.
    /// The matching lives in `WorkspaceChatVM+Intents`; the slot has to be here
    /// because an extension cannot hold storage.
    var onIntent: ((Intent) -> String?)?

    /// Which summarizer tier to answer with. Set by the workspace from the
    /// Models screen.
    ///
    /// Empty used to mean "let the backend choose", which read as harmless and
    /// was not: `resolve_tier(None)` picks the default for this Mac, so a chat
    /// ignored the tier the user had chosen — and, worse, asked for *different*
    /// weights than the warmup and the summary had loaded. `pool.acquire`
    /// closes the resident model when the key differs, so alternating a chat
    /// message with a summary swapped gigabytes each way and threw the warmup
    /// out every time.
    ///
    /// Only the tier travels. The sampling sliders are the *summarizer's* — a
    /// `max_tokens` lowered to keep an extraction terse would silently cut chat
    /// answers off — and `output_language` is about a summary's language, while
    /// the capability sheet already tells the model to answer in the user's.
    var modelTier: String = ""

    /// What is loaded, in one sentence for the model. Set by the workspace.
    var context: String = ""

    /// The open artifact's own text — the transcript, or the summary once one
    /// exists. A sentence saying "a transcript is loaded" lets the model talk
    /// *about* it and nothing more; the user would have to paste back the very
    /// thing on screen in front of both of them to ask a question about it.
    /// Budgeted on the Python side, where the model's context size is known.
    var artifact: String = ""

    func send(_ text: String) {
        let question = text.trimmingCharacters(in: .whitespacesAndNewlines)
        // A paste on its own is a question: "here, look at this".
        guard !question.isEmpty || pasted != nil else { return }
        if isAnswering { cancel() }
        draft = ""
        let material = pasted
        pasted = nil
        turns.append(ChatTurn(role: .user, text: question, pasted: material))

        if let intent = Self.intent(in: question), let reply = onIntent?(intent) {
            turns.append(ChatTurn(role: .assistant, text: reply, source: .written))
            return
        }
        ask(question)
    }

    private func ask(_ question: String) {
        isAnswering = true
        turns.append(ChatTurn(role: .assistant, text: "", isStreaming: true, source: .model))
        let index = turns.count - 1
        // Pasted material travels with the turn it came in on: it is why the
        // question was asked, and a history without it reads as a question
        // about nothing.
        let history = turns.dropLast().map { turn -> [String: String] in
            let body = turn.pasted.map { "\(turn.text)\n\n\($0)" } ?? turn.text
            return ["role": turn.role == .user ? "user" : "assistant", "content": body]
        }

        streamTask?.cancel()
        streamTask = Task { [weak self] in
            guard let self else { return }
            var sawAnything = false
            var params: [String: Any] = [
                "messages": history, "context": context, "artifact": artifact
            ]
            if !modelTier.isEmpty { params["tier"] = modelTier }
            for await message in await backend.execute(command: "chat", params: params) {
                if Task.isCancelled { break }
                guard index < turns.count else { return }
                if absorb(message, into: index) { sawAnything = true }
            }
            guard index < turns.count else { return }
            if !sawAnything {
                turns[index].text = Self.failureText(nil)
            }
            turns[index].isStreaming = false
            isAnswering = false
        }
    }

    /// One streamed message, folded into the turn being written.
    ///
    /// Split out of the loop because the loop had grown to the point where the
    /// linter counted eleven branches in it — and because "what a message does
    /// to a turn" is a different question from "how the stream is consumed".
    /// Returns whether anything landed, which is how an empty answer is told
    /// apart from a backend that never spoke.
    private func absorb(_ message: BackendMessage, into index: Int) -> Bool {
        switch message.type {
        case "chat":
            if message.thinking == true {
                turns[index].isThinking = true
                return false
            }
            guard let delta = message.delta else { return false }
            turns[index].isThinking = false
            turns[index].text += delta
            return true
        case "result":
            turns[index].stats = message.stats
            return false
        case "error":
            turns[index].text = Self.failureText(message.message)
            return true
        default:
            return false
        }
    }

    /// A local model that will not load is a fixable situation, so say which
    /// one it is rather than apologising in the abstract.
    private static func failureText(_ detail: String?) -> String {
        let base = "I couldn't reach the local model just now — it may not be "
            + "downloaded yet. Models are on the Models screen. Everything else "
            + "on this screen still works: drop a file in and I'll get to work."
        guard let detail, !detail.isEmpty else { return base }
        return base + "\n\n_\(detail)_"
    }

    func cancel() {
        streamTask?.cancel()
        streamTask = nil
        if let last = turns.indices.last, turns[last].isStreaming {
            turns[last].isStreaming = false
            if turns[last].text.isEmpty { turns.removeLast() }
        }
        isAnswering = false
    }

    func reset() {
        cancel()
        turns = []
        draft = ""
    }
}
